/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendatelefonicaconbdinterface;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LilCucumbah
 */
public class NuevoContactoJDialog extends javax.swing.JDialog {
    
    AgendaTelefonica agenda = null;

    /**
     * Creates new form NuevoContactoJDialog
     */
    
    public NuevoContactoJDialog(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);
        agenda = new AgendaTelefonica("agendaTel","agenda");
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nombrejLabel = new javax.swing.JLabel();
        telefonojLabel = new javax.swing.JLabel();
        telefonojTextField = new javax.swing.JTextField();
        nombrejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        agregarjButton1 = new javax.swing.JButton();
        borrarjButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        nombrejLabel.setText("Nombre");

        telefonojLabel.setText("Teléfono");

        telefonojTextField.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        telefonojTextField.setText("\"Escriba un Teléfono\"");
        telefonojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonojTextFieldActionPerformed(evt);
            }
        });
        telefonojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonojTextFieldKeyPressed(evt);
            }
        });

        nombrejTextField.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        nombrejTextField.setText("\"Escriba un Nombre\"");
        nombrejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrejTextFieldActionPerformed(evt);
            }
        });
        nombrejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombrejTextFieldKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Nuevo Contacto");

        agregarjButton1.setText("Agregar");
        agregarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarjButton1ActionPerformed(evt);
            }
        });

        borrarjButton.setText("Borrar");
        borrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonojLabel)
                            .addComponent(nombrejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarjButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombrejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonojTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonojLabel)
                    .addComponent(telefonojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarjButton1)
                    .addComponent(borrarjButton))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonojTextFieldActionPerformed

    private void nombrejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrejTextFieldActionPerformed

    private void borrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarjButtonActionPerformed
        
        nombrejTextField.setFont(new java.awt.Font("Tahoma", 2, 10));
        telefonojTextField.setFont(new java.awt.Font("Tahoma", 2, 10));
        nombrejTextField.setText("\"Escriba un Nombre\"");
        telefonojTextField.setText("\"Escriba un Teléfono\"");
    }//GEN-LAST:event_borrarjButtonActionPerformed

    private void agregarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarjButton1ActionPerformed
        
        Contacto contacto = null;
        String nombre, telefono;
        boolean esNombreValido = true, esTelefonoValido = true;
        nombre = nombrejTextField.getText();
        telefono = telefonojTextField.getText();
        
        if (nombre.length() == 0 || telefono.length() == 0) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Error. No ha rellenado los 2 campos necesarops para para agregar el contacto");
        
        }else{
            
            for (int i = 0; i < nombre.length(); i++) {
                if(!FuncionesSobreCaracteres.esCaracterAlfabetico(nombre.charAt(i))){
                    esNombreValido=false;
                }
            }
            for (int i = 0; i < telefono.length(); i++) {
                if(!FuncionesSobreCaracteres.esNumeroValido(telefono.charAt(i))){
                    esTelefonoValido=false;
                }
            }
            
            if (!esNombreValido) {
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Error ha "
                        + "usado carácteres no válidos en el campo NOMBRE");                
            }else if (!esTelefonoValido || telefono.length() != 9){ 
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Error ha "
                        + "usado carácteres no válidos en el campo TELÉFONO o ha"
                        + " introducido un número de dígitos distinto a 9");
            }else{
                contacto = new Contacto(nombre.toLowerCase(), telefono.toLowerCase());
            }
            try {
                if (agenda.seRepiteTelefono(telefono)) {
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Error. El telefono"
                        + " que intenta agregar ya que encuentra en la agenda");
                    
                }else{
                    agenda.añade(contacto);
                    javax.swing.JOptionPane.showMessageDialog(rootPane, "Se ha agregado su contacto:\n" + contacto + "\n satisfactoriamente");
                    dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(NuevoContactoJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_agregarjButton1ActionPerformed

    private void nombrejTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrejTextFieldKeyPressed
        
        if (nombrejTextField.getText().compareTo("\"Escriba un Nombre\"")==0) {
            nombrejTextField.setFont(new java.awt.Font("Tahoma", 0, 11));
            nombrejTextField.setText("");
        }
       
        
    }//GEN-LAST:event_nombrejTextFieldKeyPressed

    private void telefonojTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonojTextFieldKeyPressed
        
        if (telefonojTextField.getText().compareTo("\"Escriba un Teléfono\"")==0) {
            telefonojTextField.setFont(new java.awt.Font("Tahoma", 0, 11));
            telefonojTextField.setText("");
        }
        
        
    }//GEN-LAST:event_telefonojTextFieldKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            agenda.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(NuevoContactoJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoContactoJDialog dialog = null;
                try {
                    dialog = new NuevoContactoJDialog(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoContactoJDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NuevoContactoJDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarjButton1;
    private javax.swing.JButton borrarjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nombrejLabel;
    private javax.swing.JTextField nombrejTextField;
    private javax.swing.JLabel telefonojLabel;
    private javax.swing.JTextField telefonojTextField;
    // End of variables declaration//GEN-END:variables
}
